const types = {
    GET_COUNTRY_DETAILS_REQUEST :"GET_COUNTRY_DETAILS_REQUEST",
    GET_COUNTRY_DETAILS_SUCCESS :"GET_COUNTRY_DETAILS_SUCCESS",
    GET_COUNTRY_DETAILS_FAILURE :"GET_COUNTRY_DETAILS_FAILURE",
}

export default types;